#!/bin/bash

echo "Running Black formatter..."

STAGED_FILES=$(git diff --cached --name-only --diff-filter=AM | grep -E '\.py$')

if [ -z "$STAGED_FILES" ]; then
    echo "No Python files to format."
    exit 0
fi

black $STAGED_FILES
git add $STAGED_FILES

echo "Formatting complete!"
exit 0
